version: "2.1"
orbs:
    path-filtering: circleci/path-filtering@0.0.2

parameters:
  p1:
    type: boolean
    default: false
  p2:
    type: boolean
    default: false

workflows:
    generate-config:
        jobs:
            - path-filtering/filter:
                base-revision: main
                config-path: .circleci/continue-config.yml
                mapping: |
                    a/.* p1 true
                    b/.* p2 true

    other:
        when: 
            or: [<< pipeline.parameters.p1 >>, << pipeline.parameters.p2 >>]
        jobs:
            - run: echo P1:<< pipeline.parameters.p1 >>
            - run: echo P2:<< pipeline.parameters.p2 >>
