version: "2.1"

setup: true

orbs:
    path-filtering: circleci/path-filtering@0.0.2

workflows:
    generate-config:
        jobs:
            - path-filtering/filter:
                base-revision: master
                config-path: .circleci/continue.yml
                mapping: |
                    a/.* p1 true
                    b/.* p2 true
