version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the path-filtering orb is required to continue a pipeline based on the path of an updated fileset
# the maven orb is also used, as an example on using dynamic configuration to build a Java project.
orbs:
  path-filtering: circleci/path-filtering@0.0.2

# the default pipeline parameters, which will be updated according to the results of the path-filtering orb
parameters:
  run-project-a:
    type: boolean
    default: false
  run-project-b:
    type: boolean
    default: false

# our defined jobs
jobs:
  check-updated-files:
    - path-filtering/filter:
        # 3-column, whitespace-delimited mapping. One mapping per line: <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>.
        mapping: |
          project-a/.* run-project-a true
          project-b/.* run-project-b true
        base-revision: master
        # this is the path of the configuration we should trigger once path filtering and pipeline parameter value updates are complete. In this case, we are using the parent dynamic configuration itself.
        config-path: ".circleci/config.yml"
        
  build-project-a:
    - run: echo "A"

  build-project-b:
    - run: echo "B"


# our conditionally executed workflows, based on the results of the pipeline parameter values
workflows:
  project-a:
    when: << pipeline.parameters.run-project-a >>
    jobs:
      - build-service-1
  project-b:
    when: << pipeline.parameters.run-project-b >>
    jobs:
      - build-service-2
  always-run:
    jobs:
      - check-updated-files
