version: "2.1"

parameters:
  p1:
    type: boolean
    default: false
  p2:
    type: boolean
    default: false

executors:
  docker:
    docker:
        - image: circleci/python:3.7

jobs:
    run-stuff:
        executor: docker
        steps:
            - run: echo P1:<< pipeline.parameters.p1 >>
            - run: echo P2:<< pipeline.parameters.p2 >>


workflows:
    run-stuff-wf:
        when: 
            or: [<< pipeline.parameters.p1 >>, << pipeline.parameters.p2 >>]
        jobs:
            - run-stuff
